version: '3.8'

services:
  # Service pour la base de données
  mongodb:
    image: mongo:6.0  # <--- CHANGÉ : On fixe la version 6 pour éviter les conflits
    container_name: mongodb_taskflow
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # Service pour ton application Node.js
  app:
    build: .
    container_name: node_app_taskflow
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/taskflow
      - PORT=5001
      - JWT_SECRET=monSuperSecretE5_2026
    depends_on:
      - mongodb

volumes:
  mongo-data: